enum ACTIONS {
    ADD_BOARD,
    ADD_TASK,
    DELETE_BOARD,
    DELETE_TASK,
    UPDATE_BOARD,
    UPDATE_TASK,
    REORDER_COLUMNS,
    REORDER_TASKS,
    TOGGLE_SIDE_BAR,
    SET_CURRENT,
    TOGGLE_SUBTASK,
    SET_DIALOG_MODE,
}

export default ACTIONS;
