enum ACTIONS {
    ADD_BOARD,
    ADD_TASK,
    DELETE_BOARD,
    UPDATE_BOARD,
    UPDATE_TASK,
    REORDER_COLUMNS,
    TOGGLE_SIDE_BAR,
    SET_CURRENT_BOARD,
    SET_CURRENT_TASK,
    SET_DIALOG_MODE,
}

export default ACTIONS;
